services:
  - type: web
    name: daily-task-tracker
    runtime: docker
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false
